services:
  zookeeper:
    image: zookeeper
    restart: always
    hostname: zookeeper
    ports:
      - 2181:2181
    environment:
      ZOO_MY_ID: 1
      ZOO_SERVERS: server.1=zoo1:2888:3888;2181

  broker:
    image: apache/kafka:latest
    container_name: broker
    ports:
      - 9092:9092
      - 9093:9093
      - 19092:19092
      - 29093:29093
    environment:
      KAFKA_NODE_ID: 1
      KAFKA_LISTENER_SECURITY_PROTOCOL_MAP: 'CONTROLLER:PLAINTEXT,PLAINTEXT:PLAINTEXT,PLAINTEXT_HOST:PLAINTEXT'
      KAFKA_ADVERTISED_LISTENERS: 'PLAINTEXT_HOST://localhost:9092,PLAINTEXT://broker:19092'
      KAFKA_PROCESS_ROLES: 'broker,controller'
      KAFKA_CONTROLLER_QUORUM_VOTERS: '1@broker:29093'
      KAFKA_LISTENERS: 'CONTROLLER://:29093,PLAINTEXT_HOST://:9092,PLAINTEXT://:19092'
      KAFKA_INTER_BROKER_LISTENER_NAME: 'PLAINTEXT'
      KAFKA_CONTROLLER_LISTENER_NAMES: 'CONTROLLER'
      CLUSTER_ID: '4L6g3nShT-eMCtK--X86sw'
      KAFKA_OFFSETS_TOPIC_REPLICATION_FACTOR: 1
      KAFKA_GROUP_INITIAL_REBALANCE_DELAY_MS: 0
      KAFKA_TRANSACTION_STATE_LOG_MIN_ISR: 1
      KAFKA_TRANSACTION_STATE_LOG_REPLICATION_FACTOR: 1
      CONFLUENT_METRICS_REPORTER_BOOTSTRAP_SERVERS: 'broker:29092'
      KAFKA_LOG_DIRS: '/tmp/kraft-combined-logs'

  generator:
    image: python:bullseye
    container_name: generator_app
    build: .
    depends_on:
      - broker
      - zookeeper
    command: /bin/bash -c "python3 data_generator.py"

  stream:
    image: python:bullseye
    container_name: stream_app
    build: .
    depends_on:
      - broker
      - zookeeper
    command: /bin/bash -c "python3 stream.py worker -l info"

#  control-center:
#    image: confluentinc/cp-enterprise-control-center
#    hostname: control-center
#    container_name: control-center
#    depends_on:
#      - broker
#    ports:
#      - "9021:9021"
#    environment:
#      CONTROL_CENTER_BOOTSTRAP_SERVERS: 'broker:9092'
#      PORT: 9021
